<a href="https://colab.research.google.com/github/chornamarta/FakeNewsRussianUkraineWar/blob/main/Module%202/Linear%20Regression/HW_2_1_4_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
vector = np.random.rand(10)
vector

array([0.41129875, 0.7276325 , 0.3063846 , 0.34919188, 0.27365672,
       0.60972717, 0.4865007 , 0.13201155, 0.1527103 , 0.0548802 ])

In [3]:
vector.shape

(10,)

In [4]:
matrix = np.array([[11,14,17],
                   [20,23,26],
                   [29,32,35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [5]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
vector10 = np.round(vector,2) + 10
vector10

array([10.41, 10.73, 10.31, 10.35, 10.27, 10.61, 10.49, 10.13, 10.15,
       10.05])

In [7]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [8]:
vector_sqr = np.round(vector,2)**2
vector_sqr

array([0.1681, 0.5329, 0.0961, 0.1225, 0.0729, 0.3721, 0.2401, 0.0169,
       0.0225, 0.0025])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [10]:
result_matrix = np.dot(B,A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [11]:
matr_vec = np.dot(result_matrix,C)
matr_vec

array([[0.5202],
       [0.2846]])

In [12]:
matr_matr = np.dot(result_matrix,D)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [13]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [14]:
vector.T

array([0.41129875, 0.7276325 , 0.3063846 , 0.34919188, 0.27365672,
       0.60972717, 0.4865007 , 0.13201155, 0.1527103 , 0.0548802 ])

зміни нема, тому що тут 1 рядок нема на що змінювати

In [15]:
column_vector = np.expand_dims(vector,axis=1)
column_vector

array([[0.41129875],
       [0.7276325 ],
       [0.3063846 ],
       [0.34919188],
       [0.27365672],
       [0.60972717],
       [0.4865007 ],
       [0.13201155],
       [0.1527103 ],
       [0.0548802 ]])

тепер вектор має вигляд колонки, а не рядка

по суті це тепер 10 рядків

In [16]:
column_vector.T

array([[0.41129875, 0.7276325 , 0.3063846 , 0.34919188, 0.27365672,
        0.60972717, 0.4865007 , 0.13201155, 0.1527103 , 0.0548802 ]])

In [17]:
column_vector.T.shape

(1, 10)